sudo: required
language: node_js
node_js:
  - "8.1.4"
#cache:
#  directories:
#    - "node_modules"
script:
#  - npm run test
  - echo "END SCRIPT"
after_success:
  - echo "AFTER SUCCESS"
deploy:
  provider: script
  script: chmod +x ./teste.sh && ./teste.sh
  on:
    all_branches: true
