sudo: required
language: node_js
node_js:
  - "8.1.4"
#cache:
#  directories:
#    - "node_modules"
script:
#  - npm run test
  - echo "END SCRIPT"
  - chmod u+x ./teste.sh
after_success:
  - echo "AFTER SUCCESS"
deploy:
  provider: script
  script: bash teste.sh
  on:
    all_branches: true
