sudo: required
language: node_js
node_js:
  - "8.1.4"
cache:
  directories:
    - "node_modules"
script:
  - npm run test
after_success:
  - echo "variavel teste: $test"
before_deploy:
  - chmod u+x ./deploy/deploy.sh
  - chmod u+x ./deploy/deploytest.sh
deploy:
  provider: script
  script: bash ./deploy/deploy.sh
  on:
    all_branches: true
after_deploy: 
  - ./deploy/deploytest.sh ||  echo "exibindo log do deploy:" && cat ./deploy_log.txt && travis_terminate 1;
  - echo "exibindo log do deploy:"
  - cat ./deploy_log.txt
